import type { PredictionManifest } from "@/types/insights";

export const simulationManifests: PredictionManifest[] = [
  {
    simId: "projectile-launcher",
    unitSlug: "kinematics",
    topicKey: "projectile-motion",
    sourceType: "native",
    promptKind: "number",
    promptLabel: "Predict the landing range",
    unitLabel: "Kinematics",
    scoringMode: "numeric",
    manualActualEntry: false,
    viewId: "sim-launcher",
    predictionPlaceholder: "Range in meters",
    actualLabel: "Measured landing range (m)",
  },
  {
    simId: "projectile-motion-phet",
    unitSlug: "kinematics",
    topicKey: "projectile-motion",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the landing range",
    unitLabel: "Kinematics",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-projectile",
    predictionPlaceholder: "Range in meters",
    actualLabel: "Measured landing range (m)",
  },
  {
    simId: "moving-man-phet",
    unitSlug: "kinematics",
    topicKey: "motion-graphs",
    sourceType: "phet",
    promptKind: "choice",
    promptLabel: "Predict the final motion direction",
    unitLabel: "Kinematics",
    scoringMode: "choice",
    manualActualEntry: true,
    viewId: "sim-moving-man",
    choiceOptions: ["left", "right", "at rest"],
    actualLabel: "Observed final motion direction",
  },
  {
    simId: "forces-and-motion-phet",
    unitSlug: "dynamics",
    topicKey: "newtons-laws",
    sourceType: "phet",
    promptKind: "choice",
    promptLabel: "Predict the block's motion trend",
    unitLabel: "Dynamics",
    scoringMode: "choice",
    manualActualEntry: true,
    viewId: "sim-forces",
    choiceOptions: ["speeds up", "slows down", "constant velocity"],
    actualLabel: "Observed motion trend",
  },
  {
    simId: "friction-phet",
    unitSlug: "dynamics",
    topicKey: "friction",
    sourceType: "phet",
    promptKind: "choice",
    promptLabel: "Predict whether the crate moves",
    unitLabel: "Dynamics",
    scoringMode: "choice",
    manualActualEntry: true,
    viewId: "sim-friction",
    choiceOptions: ["moves", "stays still"],
    actualLabel: "Observed outcome",
  },
  {
    simId: "energy-skate-park-phet",
    unitSlug: "energy",
    topicKey: "conservation-energy",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the skater's speed at the bottom",
    unitLabel: "Energy",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-skatepark",
    predictionPlaceholder: "Speed in m/s",
    actualLabel: "Measured speed at the bottom (m/s)",
  },
  {
    simId: "springs-energy-phet",
    unitSlug: "energy",
    topicKey: "potential-energy",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the maximum spring stretch",
    unitLabel: "Energy",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-springs-e",
    predictionPlaceholder: "Stretch in meters",
    actualLabel: "Measured maximum stretch (m)",
  },
  {
    simId: "collision-simulator",
    unitSlug: "momentum",
    topicKey: "elastic-collisions",
    sourceType: "native",
    promptKind: "number",
    promptLabel: "Predict cart 1 final velocity",
    unitLabel: "Momentum",
    scoringMode: "numeric",
    manualActualEntry: false,
    viewId: "sim-collision",
    predictionPlaceholder: "Final velocity in m/s",
    actualLabel: "Measured cart 1 final velocity (m/s)",
  },
  {
    simId: "collision-lab-phet",
    unitSlug: "momentum",
    topicKey: "conservation-momentum",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict total momentum after collision",
    unitLabel: "Momentum",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-collision-lab",
    predictionPlaceholder: "Momentum in kg·m/s",
    actualLabel: "Measured total momentum after collision",
  },
  {
    simId: "balancing-act-phet",
    unitSlug: "torque",
    topicKey: "rotational-equilibrium",
    sourceType: "phet",
    promptKind: "choice",
    promptLabel: "Predict the board's rotation",
    unitLabel: "Torque",
    scoringMode: "choice",
    manualActualEntry: true,
    viewId: "sim-balancing",
    choiceOptions: ["clockwise", "counterclockwise", "balanced"],
    actualLabel: "Observed rotation",
  },
  {
    simId: "torque-phet",
    unitSlug: "rotating-systems",
    topicKey: "combined-rotation",
    sourceType: "phet",
    promptKind: "choice",
    promptLabel: "Predict the direction of angular acceleration",
    unitLabel: "Rotating Systems",
    scoringMode: "choice",
    manualActualEntry: true,
    viewId: "sim-torque",
    choiceOptions: ["clockwise", "counterclockwise", "no angular acceleration"],
    actualLabel: "Observed direction",
  },
  {
    simId: "pendulum-lab-native",
    unitSlug: "oscillations",
    topicKey: "pendulum",
    sourceType: "native",
    promptKind: "number",
    promptLabel: "Predict the pendulum period",
    unitLabel: "Oscillations",
    scoringMode: "numeric",
    manualActualEntry: false,
    viewId: "sim-pendulum",
    predictionPlaceholder: "Period in seconds",
    actualLabel: "Measured period (s)",
  },
  {
    simId: "pendulum-lab-phet",
    unitSlug: "oscillations",
    topicKey: "pendulum",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the pendulum period",
    unitLabel: "Oscillations",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-pendulum-lab",
    predictionPlaceholder: "Period in seconds",
    actualLabel: "Measured period (s)",
  },
  {
    simId: "masses-and-springs-phet",
    unitSlug: "oscillations",
    topicKey: "spring-mass",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the spring period",
    unitLabel: "Oscillations",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-springs",
    predictionPlaceholder: "Period in seconds",
    actualLabel: "Measured period (s)",
  },
  {
    simId: "under-pressure-phet",
    unitSlug: "fluids",
    topicKey: "pressure",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the gauge pressure",
    unitLabel: "Fluids",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-pressure",
    predictionPlaceholder: "Pressure in Pa",
    actualLabel: "Measured gauge pressure (Pa)",
  },
  {
    simId: "fluid-flow-phet",
    unitSlug: "fluids",
    topicKey: "continuity",
    sourceType: "phet",
    promptKind: "number",
    promptLabel: "Predict the fluid speed in the narrow section",
    unitLabel: "Fluids",
    scoringMode: "numeric",
    manualActualEntry: true,
    viewId: "sim-flow",
    predictionPlaceholder: "Speed in m/s",
    actualLabel: "Measured narrow-section speed (m/s)",
  },
];

export function getSimulationManifestByViewId(viewId: string) {
  return simulationManifests.find((manifest) => manifest.viewId === viewId);
}

export function getSimulationManifestBySimId(simId: string) {
  return simulationManifests.find((manifest) => manifest.simId === simId);
}
