import type { ArcadeQuestion } from "./types";
import { pickDeterministic } from "./seeding";

export const dailyChallengeBank: ArcadeQuestion[] = [
  {
    id: "dc-kin-1",
    unitSlug: "kinematics",
    prompt: "On a velocity-time graph, the slope represents:",
    choices: ["position", "acceleration", "force", "jerk"],
    answer: 1,
    explanation: "The slope of v-t is Δv/Δt, which is acceleration.",
    tag: "graph reading",
  },
  {
    id: "dc-kin-2",
    unitSlug: "kinematics",
    prompt: "At the top of a projectile's path, the vertical velocity is zero but the acceleration is:",
    choices: ["zero", "upward", "still downward", "undefined"],
    answer: 2,
    explanation: "Gravity keeps acting throughout the motion, so acceleration remains downward.",
    tag: "projectile motion",
  },
  {
    id: "dc-dyn-1",
    unitSlug: "dynamics",
    prompt: "If the net force on an object is zero, the object must be:",
    choices: ["at rest", "moving with constant velocity", "speeding up", "slowing down"],
    answer: 1,
    explanation: "Zero net force means zero acceleration, so velocity stays constant.",
    tag: "Newton's laws",
  },
  {
    id: "dc-dyn-2",
    unitSlug: "dynamics",
    prompt: "On an incline with no friction, the force causing acceleration down the ramp is the component of:",
    choices: ["normal force", "mass", "weight", "tension"],
    answer: 2,
    explanation: "The weight component parallel to the incline drives the motion.",
    tag: "inclines",
  },
  {
    id: "dc-energy-1",
    unitSlug: "energy",
    prompt: "If no non-conservative forces act, total mechanical energy is:",
    choices: ["zero", "conserved", "always increasing", "equal to momentum"],
    answer: 1,
    explanation: "Without losses like friction, kinetic and potential energy trade off but total stays constant.",
    tag: "energy conservation",
  },
  {
    id: "dc-energy-2",
    unitSlug: "energy",
    prompt: "Power measures how quickly you transfer:",
    choices: ["velocity", "mass", "energy", "momentum"],
    answer: 2,
    explanation: "Power is the rate of energy transfer: P = ΔE/Δt.",
    tag: "power",
  },
  {
    id: "dc-mom-1",
    unitSlug: "momentum",
    prompt: "Impulse equals the change in:",
    choices: ["velocity", "force", "momentum", "acceleration"],
    answer: 2,
    explanation: "Impulse J = FΔt = Δp.",
    tag: "impulse",
  },
  {
    id: "dc-mom-2",
    unitSlug: "momentum",
    prompt: "In a perfectly inelastic collision, which quantity is guaranteed conserved for the system?",
    choices: ["kinetic energy", "momentum", "speed", "force"],
    answer: 1,
    explanation: "Momentum is conserved in isolated collisions even when kinetic energy is not.",
    tag: "collisions",
  },
  {
    id: "dc-torque-1",
    unitSlug: "torque",
    prompt: "Torque increases when the lever arm is:",
    choices: ["shorter", "perpendicular and longer", "parallel", "zero"],
    answer: 1,
    explanation: "Torque magnitude is τ = rF sinθ, so a longer perpendicular distance gives more torque.",
    tag: "torque",
  },
  {
    id: "dc-torque-2",
    unitSlug: "torque",
    prompt: "Rotational equilibrium requires:",
    choices: ["Στ = 0 only", "ΣF = 0 only", "ΣF = 0 and Στ = 0", "constant angular speed only"],
    answer: 2,
    explanation: "Balanced translation and balanced rotation are both required.",
    tag: "equilibrium",
  },
  {
    id: "dc-rot-1",
    unitSlug: "rotating-systems",
    prompt: "If angular momentum is conserved and moment of inertia increases, angular speed must:",
    choices: ["increase", "decrease", "stay the same", "become zero immediately"],
    answer: 1,
    explanation: "Since L = Iω stays constant, ω decreases when I increases.",
    tag: "angular momentum",
  },
  {
    id: "dc-rot-2",
    unitSlug: "rotating-systems",
    prompt: "Rolling without slipping means:",
    choices: ["v = ω/r", "v = rω", "a = r/ω", "τ = I/r"],
    answer: 1,
    explanation: "The linear speed of the center is v = rω.",
    tag: "rolling motion",
  },
  {
    id: "dc-osc-1",
    unitSlug: "oscillations",
    prompt: "For a spring-mass system, increasing the mass makes the period:",
    choices: ["smaller", "larger", "zero", "unchanged"],
    answer: 1,
    explanation: "T = 2π√(m/k), so a larger mass gives a longer period.",
    tag: "springs",
  },
  {
    id: "dc-osc-2",
    unitSlug: "oscillations",
    prompt: "At maximum displacement in SHM, the speed is:",
    choices: ["maximum", "minimum", "zero", "negative only"],
    answer: 2,
    explanation: "The object stops and reverses at the endpoints, so the speed is zero there.",
    tag: "SHM energy",
  },
  {
    id: "dc-fluid-1",
    unitSlug: "fluids",
    prompt: "Fluid pressure due to depth increases with:",
    choices: ["temperature only", "depth", "surface area", "volume only"],
    answer: 1,
    explanation: "Hydrostatic pressure follows P = ρgh, so it grows with depth.",
    tag: "pressure",
  },
  {
    id: "dc-fluid-2",
    unitSlug: "fluids",
    prompt: "In an ideal fluid moving through a narrower pipe section, the speed generally:",
    choices: ["decreases", "stays the same", "increases", "becomes zero"],
    answer: 2,
    explanation: "Continuity says Av stays constant, so smaller area means larger speed.",
    tag: "continuity",
  },
];

export function getDailyChallenge(dateKey: string): ArcadeQuestion[] {
  return pickDeterministic(dailyChallengeBank, `daily:${dateKey}`, 5);
}
