import type { FlashcardDeck } from "@/content/schema";

export const momentumFlashcards: FlashcardDeck = [
  { front: "Define linear momentum.", back: "p = mv. The product of mass and velocity. A vector quantity measured in kg·m/s.", topic: "momentum-impulse" },
  { front: "Is momentum a scalar or vector?", back: "Vector — it has the same direction as velocity.", topic: "momentum-impulse" },
  { front: "SI unit of momentum?", back: "kg·m/s (equivalently N·s)", topic: "momentum-impulse" },
  { front: "What is impulse?", back: "J = FΔt = Δp. The product of force and time interval, equal to the change in momentum.", topic: "impulse-force" },
  { front: "State the Impulse-Momentum Theorem.", back: "The net impulse on an object equals its change in momentum: J = Δp = mvf − mvi.", topic: "impulse-force" },
  { front: "How is impulse found from a F-t graph?", back: "Impulse = area under the Force vs. Time curve.", topic: "impulse-force" },
  { front: "Why do airbags reduce injury?", back: "They increase the collision time Δt, reducing the average force F while keeping impulse (Δp) the same.", topic: "impulse-force" },
  { front: "When is momentum conserved?", back: "When the net external force on the system is zero (isolated system).", topic: "conservation-momentum" },
  { front: "Write the conservation of momentum equation for two objects.", back: "m₁v₁ᵢ + m₂v₂ᵢ = m₁v₁f + m₂v₂f", topic: "conservation-momentum" },
  { front: "Do internal forces affect total momentum?", back: "No. Internal forces are equal and opposite (Newton's 3rd law) and cancel out.", topic: "conservation-momentum" },
  { front: "Does momentum conservation apply in 2D?", back: "Yes — independently in the x and y directions.", topic: "conservation-momentum" },
  { front: "What is an elastic collision?", back: "A collision in which both momentum AND kinetic energy are conserved.", topic: "elastic-collisions" },
  { front: "Give an example of a nearly elastic collision.", back: "Billiard ball collisions, steel ball bearings, atomic/molecular collisions.", topic: "elastic-collisions" },
  { front: "Equal-mass elastic collision with one at rest: what happens?", back: "The objects exchange velocities. The moving one stops, the stationary one moves at the original speed.", topic: "elastic-collisions" },
  { front: "Elastic collision formula for v₁f (target at rest)?", back: "v₁f = v₁ᵢ(m₁ − m₂)/(m₁ + m₂)", topic: "elastic-collisions" },
  { front: "Elastic collision formula for v₂f (target at rest)?", back: "v₂f = 2m₁v₁ᵢ/(m₁ + m₂)", topic: "elastic-collisions" },
  { front: "What is a perfectly inelastic collision?", back: "A collision where the objects stick together and move with a common final velocity. Maximum KE is lost.", topic: "inelastic-collisions" },
  { front: "Perfectly inelastic collision formula?", back: "m₁v₁ᵢ + m₂v₂ᵢ = (m₁ + m₂)vf", topic: "inelastic-collisions" },
  { front: "Where does 'lost' KE go in an inelastic collision?", back: "Converted to thermal energy (heat), sound, and permanent deformation.", topic: "inelastic-collisions" },
  { front: "How do you check if a collision is elastic?", back: "Calculate total KE before and after. If they're equal, it's elastic.", topic: "elastic-collisions" },
  { front: "What is a 'system' in momentum problems?", back: "The collection of objects being analyzed. Only external forces on this system can change its total momentum.", topic: "conservation-momentum" },
  { front: "Newton's 2nd law in terms of momentum?", back: "F_net = dp/dt (the net force equals the rate of change of momentum).", topic: "impulse-force" },
  { front: "What fraction of KE is lost when equal masses collide perfectly inelastically (one at rest)?", back: "50% of the initial KE is lost.", topic: "inelastic-collisions" },
  { front: "In an explosion from rest, what is the total final momentum?", back: "Zero — momentum is conserved, and the initial momentum was zero.", topic: "conservation-momentum" },
  { front: "Rocket propulsion uses which conservation law?", back: "Conservation of momentum. Exhaust goes backward, rocket goes forward.", topic: "conservation-momentum" },
  { front: "How does doubling velocity affect momentum vs. KE?", back: "Momentum doubles (p = mv), but KE quadruples (KE = ½mv²).", topic: "momentum-impulse" },
  { front: "A ball bouncing vs. sticking to a wall: which has more impulse from the wall?", back: "The bouncing ball — it undergoes a larger change in momentum (reversal of direction).", topic: "impulse-force" },
];
