import type { FlashcardDeck } from "@/content/schema";

export const kinematicsFlashcards: FlashcardDeck = [
  { id: 1, topic: "Position", front: "Define displacement.", back: "Displacement is the change in position: Δx = x_f − x_i. It's a vector (has direction). Unlike distance, it can be negative." },
  { id: 2, topic: "Position", front: "What is the difference between distance and displacement?", back: "Distance is total path length (scalar, always ≥ 0). Displacement is the straight-line change in position (vector, can be negative)." },
  { id: 3, topic: "Velocity", front: "Define average velocity.", back: "v_avg = Δx/Δt. It's displacement divided by time — a vector quantity. Not the same as average speed unless motion is in one direction." },
  { id: 4, topic: "Velocity", front: "What does instantaneous velocity mean?", back: "The velocity at a single instant in time. It equals the slope of the x-t graph at that point, or the limit of Δx/Δt as Δt → 0." },
  { id: 5, topic: "Velocity", front: "Can speed be negative?", back: "No. Speed = |velocity| is always ≥ 0. Velocity can be negative (indicating direction)." },
  { id: 6, topic: "Acceleration", front: "Define acceleration.", back: "a = Δv/Δt. The rate of change of velocity. Units: m/s². It's a vector — direction matters." },
  { id: 7, topic: "Acceleration", front: "Can an object accelerate while having zero velocity?", back: "Yes! Example: a ball at the peak of its trajectory has v = 0 but a = −9.8 m/s² (gravity still acts)." },
  { id: 8, topic: "Acceleration", front: "Does negative acceleration always mean slowing down?", back: "No. If v < 0 and a < 0, the object speeds up in the negative direction. 'Slowing down' = v and a have opposite signs." },
  { id: 9, topic: "Equations", front: "List the four kinematic equations.", back: "1) v = v₀ + at\n2) x = x₀ + v₀t + ½at²\n3) v² = v₀² + 2a(x−x₀)\n4) x = x₀ + ½(v₀+v)t\nAll require constant acceleration." },
  { id: 10, topic: "Equations", front: "Which kinematic equation has no x (displacement)?", back: "v = v₀ + at. Use this when you know v₀, a, and t, and want v (or vice versa)." },
  { id: 11, topic: "Equations", front: "Which kinematic equation has no time (t)?", back: "v² = v₀² + 2a(x−x₀). Very useful for problems where time is not given or asked for." },
  { id: 12, topic: "Free Fall", front: "What is free fall?", back: "Motion under gravity alone (no air resistance). a = g = 9.8 m/s² downward for all objects, regardless of mass." },
  { id: 13, topic: "Free Fall", front: "A ball is thrown up at 20 m/s. What is its velocity at the top?", back: "v = 0 m/s at the very top. But acceleration is still −9.8 m/s² (gravity never turns off)." },
  { id: 14, topic: "Projectile", front: "What are the two independent components of projectile motion?", back: "Horizontal (x): aₓ = 0, vₓ = constant\nVertical (y): aᵧ = −g, vᵧ changes\nThey are independent — horizontal motion doesn't affect vertical." },
  { id: 15, topic: "Projectile", front: "What is the range formula?", back: "R = v₀²sin(2θ)/g. Valid only for level ground (launch and landing at same height)." },
  { id: 16, topic: "Projectile", front: "What angle maximizes projectile range?", back: "45° (on level ground). Complementary angles (e.g., 30° and 60°) give the same range." },
  { id: 17, topic: "Projectile", front: "What is the acceleration at the peak of a projectile?", back: "Still g = 9.8 m/s² downward! Common mistake: thinking a = 0 because v_y = 0." },
  { id: 18, topic: "Graphs", front: "What does the slope of an x-t graph represent?", back: "Velocity. Steep slope = fast. Zero slope = at rest. Negative slope = moving in negative direction." },
  { id: 19, topic: "Graphs", front: "What does the slope of a v-t graph represent?", back: "Acceleration. Positive slope = speeding up (if v > 0). The slope magnitude gives |a|." },
  { id: 20, topic: "Graphs", front: "What does the area under a v-t graph represent?", back: "Displacement (Δx). Area above t-axis = positive displacement. Area below = negative displacement." },
  { id: 21, topic: "Graphs", front: "A curved x-t graph means what?", back: "Non-constant velocity → the object is accelerating. The curvature direction tells you the sign of acceleration." },
  { id: 22, topic: "Graphs", front: "A horizontal line on a v-t graph means what?", back: "Constant velocity → zero acceleration. The object moves at steady speed." },
  { id: 23, topic: "Equations", front: "How do you choose the right kinematic equation?", back: "1) List knowns (3 of 5 variables: x, v₀, v, a, t)\n2) Identify which variable you want\n3) Pick the equation that doesn't contain the one variable you neither know nor need." },
  { id: 24, topic: "Free Fall", front: "Two objects of different mass are dropped. Which lands first?", back: "They land at the same time (ignoring air resistance). Galileo demonstrated this — acceleration due to gravity is independent of mass." },
  { id: 25, topic: "Position", front: "What is a reference frame?", back: "A coordinate system from which measurements are made. All motion is relative to a chosen reference frame. Velocity depends on the observer's frame." },
];
