import type { FlashcardDeck } from "@/content/schema";

export const oscillationsFlashcards: FlashcardDeck = [
  { front: "What is Simple Harmonic Motion (SHM)?", back: "Periodic motion where the restoring force is proportional to displacement from equilibrium: F = -kx." },
  { front: "Position equation for SHM", back: "x(t) = A cos(omega*t + phi)" },
  { front: "Velocity equation for SHM", back: "v(t) = -A*omega*sin(omega*t + phi)" },
  { front: "Acceleration equation for SHM", back: "a(t) = -A*omega^2*cos(omega*t + phi) = -omega^2 * x(t)" },
  { front: "Period of a spring-mass system", back: "T = 2*pi*sqrt(m/k)" },
  { front: "Period of a simple pendulum", back: "T = 2*pi*sqrt(L/g) (small angles only)" },
  { front: "Relationship: omega and frequency", back: "omega = 2*pi*f" },
  { front: "Relationship: omega and period", back: "omega = 2*pi / T" },
  { front: "Total energy in SHM", back: "E = 1/2 * k * A^2 (constant for undamped SHM)" },
  { front: "Kinetic energy in SHM", back: "KE = 1/2 * m * v^2 = 1/2 * k * (A^2 - x^2)" },
  { front: "Potential energy in SHM (spring)", back: "PE = 1/2 * k * x^2" },
  { front: "Maximum speed in SHM", back: "v_max = A * omega (occurs at x = 0)" },
  { front: "Maximum acceleration in SHM", back: "a_max = A * omega^2 (occurs at x = +/- A)" },
  { front: "What is Hooke's Law?", back: "F = -kx, where k is the spring constant and x is displacement from equilibrium." },
  { front: "At what position is KE = PE?", back: "At x = A / sqrt(2), approximately 0.707A." },
  { front: "Effect of doubling mass on spring period", back: "Period increases by sqrt(2) since T is proportional to sqrt(m)." },
  { front: "Effect of doubling spring constant on period", back: "Period decreases by sqrt(2) since T is proportional to 1/sqrt(k)." },
  { front: "Effect of doubling pendulum length on period", back: "Period increases by sqrt(2) since T is proportional to sqrt(L)." },
  { front: "Phase relationship: velocity and position", back: "Velocity leads position by 90 degrees (pi/2 radians)." },
  { front: "Phase relationship: acceleration and position", back: "Acceleration is 180 degrees (pi radians) out of phase with position." },
  { front: "Does amplitude affect period in SHM?", back: "No. Period is independent of amplitude for ideal SHM." },
  { front: "Does mass affect pendulum period?", back: "No. Period depends only on length and gravitational acceleration." },
  { front: "Springs in parallel: effective k", back: "k_eff = k1 + k2 (forces add for same displacement)." },
  { front: "Springs in series: effective k", back: "1/k_eff = 1/k1 + 1/k2 (displacements add for same force)." },
  { front: "What is the restoring force?", back: "A force that always points toward the equilibrium position, proportional to displacement." },
  { front: "Condition for SHM", back: "The net force (or torque) must be proportional to, and opposite in direction to, the displacement from equilibrium." },
  { front: "Energy at equilibrium position", back: "All kinetic (KE = E_total, PE = 0), object at maximum speed." },
  { front: "Energy at turning points (+/- A)", back: "All potential (PE = E_total, KE = 0), object momentarily at rest." },
];
