import type { FlashcardDeck } from "@/content/schema";

export const rotatingSystemsFlashcards: FlashcardDeck = [
  { front: "Rotational kinetic energy formula", back: "KE_rot = (1/2)Iω²", topic: "rotational-ke" },
  { front: "Angular momentum formula", back: "L = Iω", topic: "angular-momentum" },
  { front: "Conservation of angular momentum condition", back: "No net external torque: I₁ω₁ = I₂ω₂", topic: "conservation-angular" },
  { front: "Rolling without slipping constraint", back: "v = Rω (contact point has zero velocity)", topic: "rolling-motion" },
  { front: "Total KE for rolling object", back: "KE = (1/2)mv² + (1/2)Iω²", topic: "rolling-motion" },
  { front: "Moment of inertia: solid cylinder", back: "I = (1/2)MR²", topic: "rotational-ke" },
  { front: "Moment of inertia: solid sphere", back: "I = (2/5)MR²", topic: "rotational-ke" },
  { front: "Moment of inertia: thin hoop", back: "I = MR²", topic: "rotational-ke" },
  { front: "Moment of inertia: hollow sphere", back: "I = (2/3)MR²", topic: "rotational-ke" },
  { front: "Moment of inertia: thin rod (center)", back: "I = (1/12)ML²", topic: "rotational-ke" },
  { front: "Moment of inertia: thin rod (end)", back: "I = (1/3)ML²", topic: "rotational-ke" },
  { front: "Parallel axis theorem", back: "I = I_cm + Md²", topic: "rotational-ke" },
  { front: "Angular impulse-momentum theorem", back: "τΔt = ΔL", topic: "angular-momentum" },
  { front: "What happens when a skater pulls arms in?", back: "I decreases, ω increases, L stays constant, KE increases", topic: "conservation-angular" },
  { front: "Speed of rolling object down incline (I = cmR²)", back: "v = √(2gh/(1 + c))", topic: "rolling-motion" },
  { front: "Which shape wins a rolling race?", back: "Solid sphere (smallest c = 2/5), mass and radius don't matter", topic: "rolling-motion" },
  { front: "Acceleration of mass on string around solid disk pulley", back: "a = mg/(m + M/2)", topic: "combined-rotation" },
  { front: "Yo-yo (solid disk) acceleration", back: "a = 2g/3 ≈ 6.53 m/s²", topic: "combined-rotation" },
  { front: "Why is T < mg for a falling yo-yo?", back: "The mass accelerates downward, so mg - T = ma, meaning T = m(g-a) < mg", topic: "combined-rotation" },
  { front: "Units of angular momentum", back: "kg·m²/s (also J·s or N·m·s)", topic: "angular-momentum" },
  { front: "Units of moment of inertia", back: "kg·m²", topic: "rotational-ke" },
  { front: "Does static friction do work in rolling?", back: "No, because the contact point has zero velocity", topic: "rolling-motion" },
  { front: "Rotational analog of F = ma", back: "τ = Iα (net torque = moment of inertia × angular acceleration)", topic: "combined-rotation" },
  { front: "Rotational analog of p = mv", back: "L = Iω (angular momentum = moment of inertia × angular velocity)", topic: "angular-momentum" },
  { front: "What provides torque for rolling on an incline?", back: "Static friction at the contact point", topic: "rolling-motion" },
  { front: "In Atwood machine with massive pulley, are tensions equal?", back: "No. T₁ ≠ T₂ because the pulley needs net torque to accelerate.", topic: "combined-rotation" },
  { front: "KE in terms of angular momentum", back: "KE = L²/(2I)", topic: "rotational-ke" },
  { front: "Why does shape (not mass/radius) determine rolling race winner?", back: "In mgh = (1/2)mv²(1+c), both m and R cancel. Only geometric factor c remains.", topic: "rolling-motion" },
];
